<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OmniSpot.Benchmarking</AssemblyName>
    <RootNamespace>OmniSpot.Benchmarking</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
    <ProjectReference Include="..\..\SmartFileLauncher.Core\SmartFileLauncher.Core.csproj" />
  </ItemGroup>
</Project>
