<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OmniSpot.ChangeFeedService</AssemblyName>
    <RootNamespace>SmartFileLauncher.ChangeFeedService</RootNamespace>
    <IsPackable>false</IsPackable>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmartFileLauncher.ChangeFeedService.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <ProjectReference Include="..\SmartFileLauncher.Core\SmartFileLauncher.Core.csproj" />
  </ItemGroup>
</Project>
